FROM python:3.11-bookworm

# Install MCR
RUN export MCR_CACHE_VERBOSE=true
RUN apt-get update -y \
 && apt-get install -y wget unzip libxext-dev libxt-dev libxmu-dev libglu1-mesa-dev libxrandr-dev build-essential git \
 && mkdir -p /tmp_mcr \
 && cd /tmp_mcr \
 && wget https://ssd.mathworks.com/supportfiles/downloads/R2022b/Release/9/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2022b_Update_9_glnxa64.zip \
 && unzip MATLAB_Runtime_R2022b_Update_9_glnxa64.zip \
 && ./install -destinationFolder /usr/local/MATLAB/MATLAB_Runtime/ -mode silent -agreeToLicense yes \
 && mkdir -p /computation \
 && mkdir /computation/groupica_v4.0.4.11 \
 && rm -rf /tmp_mcr \
 && wget -P /computation/groupica_v4.0.4.11/ https://trends-public-website-fileshare.s3.amazonaws.com/public_website_files/software/gift/software/bids/v4.0.5.2M2022b/groupica
RUN apt-get install -y libstdc++*-dev
WORKDIR /computation
COPY ./GroupICATv4.0b_standalone_sep_10_2019 /computation/GroupICATv4.0b_standalone_sep_10_2019
RUN cp /computation/groupica_v4.0.4.11/groupica /computation/GroupICATv4.0b_standalone_sep_10_2019
RUN chmod +x /computation/GroupICATv4.0b_standalone_sep_10_2019/groupica

# Environment Variables for MATLAB
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/:/usr/local/MATLAB/MATLAB_Runtime/R2022b/:/usr/local/MATLAB/MATLAB_Runtime/R2022b/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2022b/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2022b/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/MATLAB_Runtime/R2022b/sys/java/jre/glnxa64/jre/lib/amd64/server:/usr/local/MATLAB/MATLAB_Runtime/R2022b/sys/java/jre/glnxa64/jre/lib/amd64
ENV XAPPLRESDIR=/usr/local/MATLAB/MATLAB_Runtime/R2022b/X11/app-defaults
ENV MCR_CACHE_VERBOSE=true
ENV MCR_CACHE_ROOT=/tmp
ENV PATH=$PATH:/computation/groupica_v4.0.4.11:
ENV MATLAB_VER=R2022b
ENV GICA_VER=v4.0.5.2
ENV GICA_INSTALL_DIR=/computation/groupica_v4.0.4.11

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
WORKDIR /workspace/

# Copy the requirements.txt file
COPY ./requirements.txt /workspace/requirements.txt

# Install dependencies from requirements.txt
RUN python3 -m pip install -r /workspace/requirements.txt

# Clone GIFT repo and patch nipype with its GIFT interface
RUN git clone -b brad_fix_nipype https://github.com/trendscenter/gift.git /computation/gift
RUN cp -r /computation/gift/GroupICAT/icatb/nipype-0.10.0/nipype/interfaces/gift /usr/local/lib/python3.11/site-packages/nipype/interfaces/gift

ENV PYTHONPATH=/workspace/app/code/
ENV NVFLARE_POC_WORKSPACE=/workspace/poc-workspace

CMD ["/bin/bash"]
